exchanges:
  - name: binance
    url: wss://stream.binance.com:443
    symbols:
      - BTCUSDT
      - ETHUSDT
  - name: okx
    url: wss://ws.okx.com:8443
    symbols:
      - BTC-USDT
      - ETH-USDT
